### PR TITLE
Add addRole method

### PR DESCRIPTION
**Pull request by Tathanen**
@jrit pretty self explanatory, makes for easier roll-adding if a user takes some action that expands their permissions

### CODE REVIEW

**Comment by jrit** [comment]
LGTM, but it doesn't seem that tests are running on the PR. Can you set this up to run on Travis?

**Comment by Tathanen** [comment]
What does that entail beyond just dropping the ng-api travis yml file in here?  Do I need to actually configure something on the travis website in some vokal account I may or may not have access to?

**Comment by jrit** [comment]
I turned it on, so just add the yml file. You should be able to get to this page https://travis-ci.org/vokal/route-auth

**Comment by Tathanen** [comment]
cha-ching

**Pull request merged**
